Pdm2Pcm:

DCRemoval:

VAD:

AGC:

STFT:

NoiseReduction:

PitchEstimation:

SpeechSpeed:

DI:
  decimation_factor: 4
  interpolation_factor: 5

SSB:


example:
  number_of_frames: 10
  filter: 'lowpass' # 'lowpass', 'highpass', 'bandpass', 'bandstop'
  remove_dc: true
