Pdm2Pcm:
user_pdm_file_path:'path_to_pdm_file.txt'
pcm_sample_rate:8000  
decimation_factor:64  
order:4 

DCRemoval:
cutoff_frequency:100
numtaps=4400

VAD:

AGC:

STFT:

NoiseReduction:

PitchEstimation:

SpeechSpeed:

DI:
  decimation_factor: 4
  interpolation_factor: 5

SSB:


example:
  number_of_frames: 10
  filter: 'lowpass' # 'lowpass', 'highpass', 'bandpass', 'bandstop'
  remove_dc: true
